import streamlit as st
def introduction():
    st.header("🎉 Chào Mừng Bạn Đến Với Ứng Dụng Quản Lý Thời Gian và Lịch Trình")
    st.markdown("""
                        Trong môi trường học tập hiện đại, việc quản lý thời gian hiệu quả là yếu tố quan trọng quyết định đến thành công của mỗi cá nhân. Sinh viên thường phải đối mặt với nhiều nhiệm vụ khác nhau như học tập, làm bài tập, ôn thi, tham gia các hoạt động ngoại khóa và duy trì cân bằng cuộc sống cá nhân. Tuy nhiên, không phải lúc nào sinh viên cũng có thể sắp xếp thời gian một cách khoa học và hợp lý.
                        Trong môi trường học tập hiện đại, việc quản lý thời gian hiệu quả là yếu tố quan trọng quyết định đến thành công của mỗi cá nhân. Sinh viên thường phải đối mặt với nhiều nhiệm vụ khác nhau như học tập, làm bài tập, ôn thi, tham gia các hoạt động ngoại khóa và duy trì cân bằng cuộc sống cá nhân. Tuy nhiên, không phải lúc nào sinh viên cũng có thể sắp xếp thời gian một cách khoa học và hợp lý.
                        Học kì III là thời gian sinh viên lớp DSEB 65B nói chung và các thành viên trong nhóm nói riêng tham gia vào rất nhiều hoạt động, từ số lượng môn học trên lớp nhiều nhất trong 8 kì Đại học, đến các công việc như hoạt động ngoại khóa, nghiên cứu khoa học, các cuộc thi khác, … Điều này dẫn tới nhu cầu cần xây dựng một công cụ hỗ trợ các bạn nâng cao công việc quản lí thời gian, quản lí học tập. Qua nghiên cứu và phân tích kĩ càng, nhóm quyết định lựa chọn đề tài “Web hỗ trợ quản lý thời gian thông minh” làm đề tài cho Project giữa kì của học phần “Lập trình cho Khoa học dữ liệu”.
                        Dự án "Web quản lý thời gian - học tập" được xây dựng nhằm cung cấp một giải pháp tối ưu cho việc quản lý thời gian học tập. Ứng dụng này sẽ giúp sinh viên dễ dàng lập kế hoạch, theo dõi tiến độ học tập, và đưa ra các lời khuyên dựa trên phân tích thời gian thực tế. Mục tiêu chính là giúp sinh viên cải thiện năng suất học tập, đạt được các mục tiêu đã đề ra và giảm thiểu tình trạng căng thẳng do quản lý thời gian kém.
                        Được phát triển trong khuôn khổ học phần "Lập trình cho khoa học dữ liệu", dự án còn là cơ hội để sinh viên áp dụng kiến thức lập trình vào việc xây dựng một công cụ hữu ích trong cuộc sống học tập hàng ngày. Với tính năng đơn giản nhưng hiệu quả, ứng dụng này sẽ trở thành trợ thủ đắc lực trong việc quản lý thời gian, giúp người dùng đạt hiệu quả cao hơn trong học tập và phát triển bản thân.
                        Trong môi trường học tập hiện đại, việc quản lý thời gian hiệu quả là yếu tố quan trọng quyết định đến thành công của mỗi cá nhân. Sinh viên thường phải đối mặt với nhiều nhiệm vụ khác nhau như học tập, làm bài tập, ôn thi, tham gia các hoạt động ngoại khóa và duy trì cân bằng cuộc sống cá nhân. Tuy nhiên, không phải lúc nào sinh viên cũng có thể sắp xếp thời gian một cách khoa học và hợp lý.
                        Học kì III là thời gian sinh viên lớp DSEB 65B nói chung và các thành viên trong nhóm nói riêng tham gia vào rất nhiều hoạt động, từ số lượng môn học trên lớp nhiều nhất trong 8 kì Đại học, đến các công việc như hoạt động ngoại khóa, nghiên cứu khoa học, các cuộc thi khác, … Điều này dẫn tới nhu cầu cần xây dựng một công cụ hỗ trợ các bạn nâng cao công việc quản lí thời gian, quản lí học tập. Qua nghiên cứu và phân tích kĩ càng, nhóm quyết định lựa chọn đề tài “Web hỗ trợ quản lý thời gian thông minh” làm đề tài cho Project giữa kì của học phần “Lập trình cho Khoa học dữ liệu”.
                        Dự án "Web quản lý thời gian - học tập" được xây dựng nhằm cung cấp một giải pháp tối ưu cho việc quản lý thời gian học tập. Ứng dụng này sẽ giúp sinh viên dễ dàng lập kế hoạch, theo dõi tiến độ học tập, và đưa ra các lời khuyên dựa trên phân tích thời gian thực tế. Mục tiêu chính là giúp sinh viên cải thiện năng suất học tập, đạt được các mục tiêu đã đề ra và giảm thiểu tình trạng căng thẳng do quản lý thời gian kém.
                        Được phát triển trong khuôn khổ học phần "Lập trình cho khoa học dữ liệu", dự án còn là cơ hội để sinh viên áp dụng kiến thức lập trình vào việc xây dựng một công cụ hữu ích trong cuộc sống học tập hàng ngày. Với tính năng đơn giản nhưng hiệu quả, ứng dụng này sẽ trở thành trợ thủ đắc lực trong việc quản lý thời gian, giúp người dùng đạt hiệu quả cao hơn trong học tập và phát triển bản thân.
                        Trong môi trường học tập hiện đại, việc quản lý thời gian hiệu quả là yếu tố quan trọng quyết định đến thành công của mỗi cá nhân. Sinh viên thường phải đối mặt với nhiều nhiệm vụ khác nhau như học tập, làm bài tập, ôn thi, tham gia các hoạt động ngoại khóa và duy trì cân bằng cuộc sống cá nhân. Tuy nhiên, không phải lúc nào sinh viên cũng có thể sắp xếp thời gian một cách khoa học và hợp lý.
                        Học kì III là thời gian sinh viên lớp DSEB 65B nói chung và các thành viên trong nhóm nói riêng tham gia vào rất nhiều hoạt động, từ số lượng môn học trên lớp nhiều nhất trong 8 kì Đại học, đến các công việc như hoạt động ngoại khóa, nghiên cứu khoa học, các cuộc thi khác, … Điều này dẫn tới nhu cầu cần xây dựng một công cụ hỗ trợ các bạn nâng cao công việc quản lí thời gian, quản lí học tập. Qua nghiên cứu và phân tích kĩ càng, nhóm quyết định lựa chọn đề tài “Web hỗ trợ quản lý thời gian thông minh” làm đề tài cho Project giữa kì của học phần “Lập trình cho Khoa học dữ liệu”.
                        Dự án "Web quản lý thời gian - học tập" được xây dựng nhằm cung cấp một giải pháp tối ưu cho việc quản lý thời gian học tập. Ứng dụng này sẽ giúp sinh viên dễ dàng lập kế hoạch, theo dõi tiến độ học tập, và đưa ra các lời khuyên dựa trên phân tích thời gian thực tế. Mục tiêu chính là giúp sinh viên cải thiện năng suất học tập, đạt được các mục tiêu đã đề ra và giảm thiểu tình trạng căng thẳng do quản lý thời gian kém.
                        Được phát triển trong khuôn khổ học phần "Lập trình cho khoa học dữ liệu", dự án còn là cơ hội để sinh viên áp dụng kiến thức lập trình vào việc xây dựng một công cụ hữu ích trong cuộc sống học tập hàng ngày. Với tính năng đơn giản nhưng hiệu quả, ứng dụng này sẽ trở thành trợ thủ đắc lực trong việc quản lý thời gian, giúp người dùng đạt hiệu quả cao hơn trong học tập và phát triển bản thân.
                        Trong môi trường học tập hiện đại, việc quản lý thời gian hiệu quả là yếu tố quan trọng quyết định đến thành công của mỗi cá nhân. Sinh viên thường phải đối mặt với nhiều nhiệm vụ khác nhau như học tập, làm bài tập, ôn thi, tham gia các hoạt động ngoại khóa và duy trì cân bằng cuộc sống cá nhân. Tuy nhiên, không phải lúc nào sinh viên cũng có thể sắp xếp thời gian một cách khoa học và hợp lý.
                        Học kì III là thời gian sinh viên lớp DSEB 65B nói chung và các thành viên trong nhóm nói riêng tham gia vào rất nhiều hoạt động, từ số lượng môn học trên lớp nhiều nhất trong 8 kì Đại học, đến các công việc như hoạt động ngoại khóa, nghiên cứu khoa học, các cuộc thi khác, … Điều này dẫn tới nhu cầu cần xây dựng một công cụ hỗ trợ các bạn nâng cao công việc quản lí thời gian, quản lí học tập. Qua nghiên cứu và phân tích kĩ càng, nhóm quyết định lựa chọn đề tài “Web hỗ trợ quản lý thời gian thông minh” làm đề tài cho Project giữa kì của học phần “Lập trình cho Khoa học dữ liệu”.
                        Dự án "Web quản lý thời gian - học tập" được xây dựng nhằm cung cấp một giải pháp tối ưu cho việc quản lý thời gian học tập. Ứng dụng này sẽ giúp sinh viên dễ dàng lập kế hoạch, theo dõi tiến độ học tập, và đưa ra các lời khuyên dựa trên phân tích thời gian thực tế. Mục tiêu chính là giúp sinh viên cải thiện năng suất học tập, đạt được các mục tiêu đã đề ra và giảm thiểu tình trạng căng thẳng do quản lý thời gian kém.
                        Được phát triển trong khuôn khổ học phần "Lập trình cho khoa học dữ liệu", dự án còn là cơ hội để sinh viên áp dụng kiến thức lập trình vào việc xây dựng một công cụ hữu ích trong cuộc sống học tập hàng ngày. Với tính năng đơn giản nhưng hiệu quả, ứng dụng này sẽ trở thành trợ thủ đắc lực trong việc quản lý thời gian, giúp người dùng đạt hiệu quả cao hơn trong học tập và phát triển bản thân.
                        """)
    st.markdown("""
                        Dự án "Web quản lý thời gian - học tập" được xây dựng nhằm cung cấp một giải pháp tối ưu cho việc quản lý thời gian học tập. Ứng dụng này sẽ giúp sinh viên dễ dàng lập kế hoạch, theo dõi tiến độ học tập, và đưa ra các lời khuyên dựa trên phân tích thời gian thực tế.
                        """)